apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: 
    {{ .Values.label }}
  name: nginx
spec:
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: {{ .Values.image }}
        name: nginx
        resources: {}
status: {}