apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    {{- include ".Values.labels" . | nindent 4 }}
  name: mongodb
spec:
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      labels:
        {{- include ".Values.labels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: mongodb
        ports: 
        - containerPort: {{ .Values.containerMongoport }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret1
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret1
              key: mongo-root-password
