apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    {{ .Values.label.app }}
  name: mongodb
spec:
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      {{ .Values.label.app }}
  strategy: {}
  template:
    metadata:
      labels:
        {{ .Values.label.app }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: mongodb
        ports: 
        - containerPort: {{ .Values.container-mongoport }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret1
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret1
              key: mongo-root-password
