apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{ .Values.expressNodePort }}
      targetPort: {{ .Values.expressContainerPort }}
      nodePort: {{ .Values.nodePort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    {{- include "express.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "express.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "express.labels" . | nindent 8 }}
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.expressimage }}
        ports:
        - containerPort: {{ .Values.expressContainerPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: secret1
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret1
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

