apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  selector:
    {{ .Values.label.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.nodeMongoport }}
      targetPort: {{ .Values.containerMongoport }}
