apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  labels:
    {{ .Values.label.appname }}
spec:
  selector:
    app: {{ .Values.label.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.nodeMongoport }}
      targetPort: {{ .Values.containerMongoport }}
