apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  labels:
    {{ include ".Values.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include ".Values.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.nodeMongoport }}
      targetPort: {{ .Values.containerMongoport }}
